node {

    checkout scm

    env.DOCKER_API_VERSION="1.23"
    env.http.proxyHost="proxy.sdc.hp.com"
    env.http.proxyPort="8080"
    env.https.proxyHost="proxy.sdc.hp.com"
    env.https.proxyPort="8080"
    env.http.nonProxyHosts="192.168.99.100"
    System.properties.putAll([
    'http.proxyHost':'proxy.sdc.com', 
    'http.proxyPort':'8080',
    'https.proxyHost':'proxy.sdc.com', 
    'https.proxyPort':'8080',
    'http.nonProxyHosts': '192.168.99.100'
])    
    sh "git rev-parse --short HEAD > commit-id"

    tag = readFile('commit-id').replace("\n", "").replace("\r", "")
    appName = "hello-kenzan"
    registryHost = "127.0.0.1:30912/"
    imageName = "${registryHost}${appName}:${tag}"
    env.BUILDIMG=imageName

    stage "Build"
    
        sh "docker build -t ${imageName} part1/hello-kenzan"
    
    stage "Push"

        sh "docker push ${imageName}"

    stage "Deploy"
        
        sh "kubectl cluster-info"
        sh "printenv"

        sh "sed 's#__IMAGE__#'$BUILDIMG'#' part1/hello-kenzan/k8s/deployment.yaml | kubectl apply -f -"
}
